# Generated by Django 2.1.2 on 2018-10-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='src',
            new_name='img_src',
        ),
    ]
