# Generated by Django 2.1.2 on 2018-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0002_auto_20181028_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
