# Generated by Django 2.1.2 on 2018-10-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0002_auto_20181016_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosgame',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
