# Generated by Django 2.1.2 on 2018-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0003_auto_20181028_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosgame',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
