# Generated by Django 2.1.2 on 2018-10-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0003_auto_20181017_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.URLField(max_length=255)),
                ('location_name', models.CharField(max_length=128)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosgamesfinder.DosGame')),
            ],
            options={
                'ordering': ('location_name',),
            },
        ),
    ]
