# Generated by Django 2.1.2 on 2018-11-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0004_auto_20181028_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosgame',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dosgame',
            name='short_description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
