# Generated by Django 2.1.2 on 2018-10-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0004_downloadlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlocation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_location', to='dosgamesfinder.DosGame'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot', to='dosgamesfinder.DosGame'),
        ),
    ]
