# Generated by Django 2.1.2 on 2018-11-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0005_auto_20181105_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosgame',
            name='long_description',
        ),
    ]
