# Generated by Django 2.1.2 on 2018-11-11 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0007_auto_20181105_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosgame',
            name='thumbnail_src',
            field=models.URLField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
