# Generated by Django 2.1.2 on 2018-10-18 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0008_auto_20181018_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlocation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_location_set', to='dosgamesfinder.DosGame'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosgamesfinder.DosGame'),
        ),
    ]
