# Generated by Django 2.1.2 on 2018-11-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0008_dosgame_thumbnail_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosgame',
            name='thumbnail_src',
            field=models.URLField(default='/no_screenshot.jpg', max_length=255),
        ),
    ]
