# Generated by Django 2.1.2 on 2018-11-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0009_auto_20181111_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosgame',
            name='thumbnail_src',
            field=models.CharField(default='/no_screenshot.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadlocation',
            name='href',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='img_src',
            field=models.CharField(max_length=255),
        ),
    ]
