# Generated by Django 2.1.2 on 2018-10-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0010_auto_20181018_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlocation',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='downloadlocation',
            old_name='location_name',
            new_name='name',
        ),
    ]
