# Generated by Django 2.1.2 on 2018-11-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0010_auto_20181117_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosgame',
            name='thumbnail_src',
            field=models.CharField(default='/no_screenshot.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='downloadlocation',
            name='href',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='img_src',
            field=models.CharField(max_length=256),
        ),
    ]
