# Generated by Django 2.1.2 on 2018-10-21 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dosgamesfinder', '0011_auto_20181018_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosgame',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
